import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import bcrypt from 'bcryptjs';

export const resources = ['projects','skills','experience','education','certifications','services','testimonials','posts','media','resumes','messages','activity'] as const;
export type Resource = typeof resources[number];
const file = path.resolve(process.env.DATA_FILE || 'data/database.json');
const now=()=>new Date().toISOString();
const id=()=>randomUUID();
const seed:any={
 user:{id:id(),email:process.env.ADMIN_EMAIL||'admin@atlas.dev',passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe123!',12),name:'Portfolio Owner',role:'ADMIN'},
 profile:{name:'Portfolio Owner',title:'Senior Software & Security Engineer',intro:'I architect resilient digital products at the intersection of thoughtful design, cloud engineering, and application security.',bio:'For more than eight years, I have helped ambitious teams transform complex requirements into secure, elegant software. My work spans product engineering, distributed systems, cloud infrastructure, and offensive security.',location:'Kigali, Rwanda',email:'hello@atlas.dev',phone:'+250 788 000 000',availability:'Available for select projects',years:8,heroBadge:'Engineering secure systems that scale',primaryCta:'Explore my work',secondaryCta:'Let’s talk',avatar:'',socials:{github:'https://github.com',linkedin:'https://linkedin.com',twitter:'https://x.com'}},
 settings:{siteTitle:'Developer Portfolio',metaDescription:'Portfolio of a senior software and security engineer.',sectionTitles:{projects:'Selected work',skills:'Technical capabilities',experience:'Career journey',services:'How I can help',testimonials:'Trusted by teams',contact:'Let’s build something exceptional'},footerText:'Designed and engineered with intention.',theme:{mode:'dark',primary:'#7c6cf2',secondary:'#16c1a3',accent:'#f59e61',background:'#080a0f',surface:'#10131b',text:'#f3f4f8',muted:'#9ba3b4',border:'#242938',radius:18,fontScale:1,container:1180,spacing:96,animation:'medium'}},
 navigation:[{id:id(),label:'Work',url:'#projects',enabled:true,order:1},{id:id(),label:'Expertise',url:'#skills',enabled:true,order:2},{id:id(),label:'Experience',url:'#experience',enabled:true,order:3},{id:id(),label:'Contact',url:'#contact',enabled:true,order:4}],
 projects:[
 {id:id(),name:'Sentinel Cloud',slug:'sentinel-cloud',shortDescription:'Cloud security posture management, redesigned for clarity and action.',fullDescription:'A multi-tenant security platform that turns millions of cloud signals into prioritized, actionable findings.',category:'Cybersecurity',technologies:['React','TypeScript','Go','PostgreSQL','Kubernetes'],featured:true,published:true,order:1,year:'2026',role:'Lead Engineer',image:'',results:'Reduced mean time to remediation by 64%.',createdAt:now(),updatedAt:now()},
 {id:id(),name:'Nexus Commerce',slug:'nexus-commerce',shortDescription:'A composable commerce engine powering high-volume regional marketplaces.',fullDescription:'Event-driven commerce infrastructure with an accessible operations suite.',category:'Platform',technologies:['Next.js','Node.js','Kafka','AWS'],featured:true,published:true,order:2,year:'2025',role:'Principal Developer',image:'',results:'Handled 12k orders per minute at peak.',createdAt:now(),updatedAt:now()},
 {id:id(),name:'Pulse Intelligence',slug:'pulse-intelligence',shortDescription:'Operational analytics that helps distributed teams act in real time.',fullDescription:'Privacy-conscious analytics and incident intelligence for modern operations teams.',category:'Data systems',technologies:['React','Python','ClickHouse','GCP'],featured:false,published:true,order:3,year:'2024',role:'Full-stack Engineer',image:'',results:'Improved incident detection by 41%.',createdAt:now(),updatedAt:now()}],
 skills:[['TypeScript','Frontend',94],['React & Next.js','Frontend',92],['Node.js','Backend',90],['Go','Backend',82],['PostgreSQL','Databases',88],['AWS & Kubernetes','Cloud',85],['Application Security','Cybersecurity',91],['Systems Architecture','Architecture',93]].map((x,i)=>({id:id(),name:x[0],category:x[1],proficiency:x[2],description:'Production systems, patterns, and practices.',featured:i<4,visible:true,order:i+1,createdAt:now(),updatedAt:now()})),
 experience:[{id:id(),title:'Principal Software Engineer',company:'Northstar Systems',location:'Kigali · Remote',startDate:'2023',endDate:'Present',current:true,description:'Leading platform architecture and application security across a portfolio of B2B products.',technologies:['TypeScript','Go','AWS'],visible:true,order:1,createdAt:now(),updatedAt:now()},{id:id(),title:'Senior Full-stack Engineer',company:'Vertex Labs',location:'Remote',startDate:'2020',endDate:'2023',description:'Built developer platforms and mentored a cross-functional engineering team.',technologies:['React','Node.js','PostgreSQL'],visible:true,order:2,createdAt:now(),updatedAt:now()}],
 education:[{id:id(),institution:'University of Rwanda',degree:'BSc Computer Engineering',field:'Computer Engineering',startDate:'2013',endDate:'2017',description:'Networks, distributed systems, and information security.',visible:true,order:1,createdAt:now(),updatedAt:now()}],
 certifications:[{id:id(),name:'AWS Certified Security — Specialty',organization:'Amazon Web Services',issueDate:'2025',neverExpires:false,visible:true,order:1,createdAt:now(),updatedAt:now()},{id:id(),name:'Certified Kubernetes Administrator',organization:'Cloud Native Computing Foundation',issueDate:'2024',visible:true,order:2,createdAt:now(),updatedAt:now()}],
 services:[{id:id(),title:'Product Engineering',description:'From strategy and architecture to polished, production-ready delivery.',icon:'Code2',features:['Architecture','Full-stack delivery','Design systems'],visible:true,order:1,createdAt:now(),updatedAt:now()},{id:id(),title:'Security Engineering',description:'Pragmatic security built into your product and engineering lifecycle.',icon:'Shield',features:['Threat modeling','Secure SDLC','Cloud reviews'],visible:true,order:2,createdAt:now(),updatedAt:now()},{id:id(),title:'Technical Advisory',description:'Clear technical direction for teams navigating scale and complexity.',icon:'Compass',features:['Platform strategy','Team enablement','Due diligence'],visible:true,order:3,createdAt:now(),updatedAt:now()}],
 testimonials:[{id:id(),name:'Maya Chen',position:'VP of Product',company:'Northstar',testimonial:'Alex brings rare depth across product, systems, and security. The result is software that is both elegant and genuinely resilient.',rating:5,published:true,order:1,createdAt:now(),updatedAt:now()}],
 posts:[{id:id(),title:'Designing secure systems without slowing teams down',slug:'secure-systems',excerpt:'A practical framework for making security a product capability.',content:'Security works best when it is part of everyday engineering decisions.',status:'published',published:true,readingTime:6,tags:['Security','Engineering'],createdAt:now(),updatedAt:now()}],media:[],resumes:[],messages:[],activity:[]
};
function load(){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(seed,null,2));return seed}}
let data=load();
// Backward-compatible theme migration for existing installations.
const legacy=data.settings?.theme||{};
legacy.dark ||= {primary:legacy.primary||'#7c6cf2',secondary:legacy.secondary||'#16c1a3',accent:legacy.accent||'#f59e61',background:legacy.background||'#080a0f',surface:legacy.surface||'#10131b',text:legacy.text||'#f3f4f8',muted:legacy.muted||'#9ba3b4',border:legacy.border||'#242938'};
legacy.light ||= {primary:'#6656dc',secondary:'#078b78',accent:'#d66d32',background:'#f7f8fb',surface:'#ffffff',text:'#171923',muted:'#626b7c',border:'#dfe3eb'};
data.settings.theme=legacy;
const save=()=>{const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,file)};
export const db={
 public(){const {user,messages,activity,...safe}=data;return safe},
 get(){return data},
 updateSingleton(key:string,value:any){data[key]={...data[key],...value,updatedAt:now()};save();return data[key]},
 list(r:Resource){return data[r]||[]},
 create(r:Resource,value:any){const item={...value,id:id(),createdAt:now(),updatedAt:now()};data[r].push(item);activity(r==='activity'?null:`Created ${r.slice(0,-1)}`,item.name||item.title||item.id);save();return item},
 update(r:Resource,itemId:string,value:any){const i=data[r].findIndex((x:any)=>x.id===itemId);if(i<0)return null;data[r][i]={...data[r][i],...value,id:itemId,updatedAt:now()};activity(`Updated ${r.slice(0,-1)}`,data[r][i].name||data[r][i].title||itemId);save();return data[r][i]},
 remove(r:Resource,itemId:string){const i=data[r].findIndex((x:any)=>x.id===itemId);if(i<0)return null;const [item]=data[r].splice(i,1);activity(`Deleted ${r.slice(0,-1)}`,item.name||item.title||itemId);save();return item},
 reorder(r:Resource,ids:string[]){const map=new Map(ids.map((v,i)=>[v,i+1]));data[r].forEach((x:any)=>{if(map.has(x.id))x.order=map.get(x.id)});save();return data[r]}, save
};
function activity(action:string|null,subject:string){if(!action)return;data.activity.unshift({id:id(),action,subject,createdAt:now()});data.activity=data.activity.slice(0,100)}
